name = "AOCoptimizer"
uuid = "ba4aa9bd-6938-48c2-966f-258481ba1c4a"
authors = ["kkalinin <kkalinin@microsoft.com>"]
version = "0.1.0"

[deps]

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]

[compat]
Aqua = "0.8"
JET = "0.9"
Test = "1"
julia = "1"
